[tools]
rust = { version = "1.86.0" }

[tasks.build]
dir = "."
run = ["chmod +x ./build.sh", "./build.sh"]

[tasks."update:submodules"]
dir = "."
run = [
	"git submodule update --init --recursive",
	"git submodule foreach git pull origin master",
]
