name = "MD"
description = "Fetch and process markdown files from the network"
modes = ["on_create"]
targets = ["markdown"]

[[privileges]]
identifier = "log::debug"
description = "Log debug information"

[[privileges]]
identifier = "log::error"
description = "Log error information"

[[privileges]]
identifier = "log::warn"
description = "Log warnings"

[[privileges]]
identifier = "entries::update"
description = "Update the entry's content with the downloaded Markdown"

[[privileges]]
identifier = "chunks::create"
description = "Create chunks for the entry's content"

[[privileges]]
identifier = "network::request"
description = "Fetch the content from the network"
