[tools]
rust = { version = "1.86.0" }

[tasks.build]
dir = "."
depends = ["build:wasm"]
depends_post = ["generate:checksum"]
run = ["rm output/{*.js,*.d.ts,package.json,README.md,.gitignore}"]

[tasks."build:wasm"]
dir = "."
run = "wasm-pack build --release -d output --out-name plugin.wasm"

[tasks."generate:checksum"]
dir = "output"
run = "sha256sum -b plugin.wasm | cut -d' ' -f1 | tr -d '\n' > plugin.wasm.sha256"
