[tools]
rust = { version = "1.86.0" }

[tasks.build]
dir = "."
depends = ["build:wasm"]
depends_post = ["generate:checksum"]
run = [
	"mv ./target/wasm32-unknown-unknown/release/link.wasm ./output/pre-opt.wasm",
	"wasm-opt -Oz ./output/pre-opt.wasm -o ./output/plugin.wasm",
	"rm ./output/pre-opt.wasm",
]

[tasks."build:wasm"]
dir = "."
run = "cargo build --release --target wasm32-unknown-unknown"

[tasks."generate:checksum"]
dir = "output"
run = "sha256sum -b plugin.wasm | cut -d' ' -f1 | tr -d '\n' > plugin.wasm.sha256"
