name = "Link"
description = "Convert URL content to Markdown and extract text."
modes = ["on_create"]
targets = ["link"]

[[privileges]]
identifier = "host:entries:update"
description = "Update the entry's content with the parsed Markdown"

[[privileges]]
identifier = "host:chunks:create"
description = "Create chunks for the entry's content"
