name = "Link"
description = "Convert URL content to Markdown and extract text."
modes = ["on_create"]
targets = ["link"]

[[privileges]]
identifier = "log::debug"
description = "Log debug information"

[[privileges]]
identifier = "log::error"
description = "Log error information"

[[privileges]]
identifier = "entries::update"
description = "Update the entry's content with the parsed Markdown"

[[privileges]]
identifier = "chunks::create"
description = "Create chunks for the entry's content"

[[privileges]]
identifier = "transform::chunk_with_overlap"
description = "Create chunks for the entry's content with overlap"

[[privileges]]
identifier = "transform::url_to_markdown"
description = "Transform a link's content to Markdown"
